### ISSUE TITLE
Dataset Missing

### ISSUE THREAD

**Issue by mr-ayush-agrawal** [datapublishings/Course-python-data-science#5]
For the file [covid-19_trendAnalysis.ipynb](https://github.com/datapublishings/Course-python-data-science/blob/master/covid-19_trendAnalysis.ipynb) The dataset which is imported in cell 2 is Missing 

 - [ ]  Required a file *covid_19_data.csv*

**Comment by melvernaldo** [comment]
Could anyone please share the dataset?

Edit: I found a github page with the dataset csv file.
[Link to the github page.](https://github.com/AISPUBLISHING/dnn-python-from-scratch)
